version: '3.7'
services:
  service-1:
    image: jcashen/animal-app-1
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 2
  service-2:
    image: jcashen/animal-app-2
    build: ./service2
    ports:
    - target: 5001
      protocol: tcp
    deploy:
      replicas: 2
  service-3:
    image: jcashen/animal-app-3
    build: ./service3
    ports:
    - target: 5002
      protocol: tcp
    deploy:
      replicas: 2
  service-4:
    image: jcashen/animal-app-4
    build: ./service4
    ports:
    - target: 5003
      protocol: tcp
    deploy:
      replicas: 2